### ISSUE TITLE
execute_base64_decodedpayload.txt Query Fails

### ISSUE THREAD

**Issue by Petitohead** [Azure/Orion#36]
**Describe the bug**
Query fails to run.

**To Reproduce**
1. Copy query into Kusto
2. Run Query
3. Query fails to execute and syntax errors are shown

**Expected behavior**
Query should execute without syntax errors

Fix:
Modify Line 28
FileName=tostring(split(NewProcessName, '\\')[-1], // convert SecurityEvents raw schema to get FileName & CommandLine 

To: 

FileName=tostring(split(NewProcessName, '\\')[-1]), // convert SecurityEvents raw schema to get FileName & CommandLine

**Comment by timbMSFT** [comment]
Fixed by Commit 5f097f90
